server:
  port: 8888
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/YueWang0513/aispringcloud.git
          searchPaths: config
          username: YueWang0513
          password: dayueyue88052306
      label: master
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/